title: pyJedAI
description: >- # this means to ignore newlines until "baseurl:"
  An open-source library that leverages Pythonâ€™s data science ecosystem to build powerful end-to-end Entity Resolution workflows.
# baseurl: "/pyjedai" # the subpath of your site, e.g. /blog
# url: "https://ai-team-uoa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 
github_username:  AI-team-UoA
# Build settings
theme: minima
github:
  repo:  https://ai-team-uoa.github.io/pyjedai
# google_analytics: UA-NNNNNNNN-N
